### ISSUE TITLE
Conda doesnt run

### ISSUE THREAD

**Issue by gjain75** [junegunn/vim-plug#1086]
cannot run any command to load spyder, update etc. from conda
------------------------------

```
(base) PS C:\Users\Gautam> conda update conda

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Lib\site-packages\conda\exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\Lib\site-packages\conda\cli\main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "C:\ProgramData\Anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 81, in do_call
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "C:\Users\Gautam\AppData\Local\Programs\Python\Python37\Lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\ProgramData\Anaconda3\Lib\site-packages\conda\cli\main_update.py", line 8, in <module>
    from .install import install
  File "C:\ProgramData\Anaconda3\Lib\site-packages\conda\cli\install.py", line 19, in <module>
    from ..core.index import calculate_channel_urls, get_index
  File "C:\ProgramData\Anaconda3\Lib\site-packages\conda\core\index.py", line 12, in <module>
    from .package_cache_data import PackageCacheData
  File "C:\ProgramData\Anaconda3\Lib\site-packages\conda\core\package_cache_data.py", line 14, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\ProgramData\Anaconda3\Lib\site-packages\conda\core\path_actions.py", line 13, in <module>
    from .envs_manager import get_user_environments_txt_file, register_env, unregister_env
  File "C:\ProgramData\Anaconda3\Lib\site-packages\conda\core\envs_manager.py", line 11, in <module>
    from .prefix_data import PrefixData
  File "C:\ProgramData\Anaconda3\Lib\site-packages\conda\core\prefix_data.py", line 21, in <module>
    from ..common.pkg_formats.python import get_site_packages_anchor_files
  File "C:\ProgramData\Anaconda3\Lib\site-packages\conda\common\pkg_formats\python.py", line 1169, in <module>
    DEFAULT_MARKER_CONTEXT = get_default_marker_context()
  File "C:\ProgramData\Anaconda3\Lib\site-packages\conda\common\pkg_formats\python.py", line 1151, in get_default_marker_context
    'platform_python_implementation': platform.python_implementation(),
  File "C:\Users\Gautam\AppData\Local\Programs\Python\Python37\Lib\platform.py", line 1264, in python_implementation
    return _sys_version()[0]
  File "C:\Users\Gautam\AppData\Local\Programs\Python\Python37\Lib\platform.py", line 1225, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 15:37:01) [MSC v.1916 64 bit (AMD64)]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\conda-script.py", line 12, in <module>
    sys.exit(main())
  File "C:\ProgramData\Anaconda3\Lib\site-packages\conda\cli\main.py", line 152, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\Lib\site-packages\conda\exceptions.py", line 1371, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\Lib\site-packages\conda\exceptions.py", line 1082, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "C:\ProgramData\Anaconda3\Lib\site-packages\conda\exceptions.py", line 1126, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "C:\ProgramData\Anaconda3\Lib\site-packages\conda\exceptions.py", line 1137, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "C:\ProgramData\Anaconda3\Lib\site-packages\conda\exceptions.py", line 1207, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "C:\ProgramData\Anaconda3\Lib\site-packages\conda\cli\main_info.py", line 19, in <module>
    from ..core.index import _supplement_index_with_system
  File "C:\ProgramData\Anaconda3\Lib\site-packages\conda\core\index.py", line 12, in <module>
    from .package_cache_data import PackageCacheData
  File "C:\ProgramData\Anaconda3\Lib\site-packages\conda\core\package_cache_data.py", line 14, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\ProgramData\Anaconda3\Lib\site-packages\conda\core\path_actions.py", line 13, in <module>
    from .envs_manager import get_user_environments_txt_file, register_env, unregister_env
  File "C:\ProgramData\Anaconda3\Lib\site-packages\conda\core\envs_manager.py", line 11, in <module>
    from .prefix_data import PrefixData
  File "C:\ProgramData\Anaconda3\Lib\site-packages\conda\core\prefix_data.py", line 21, in <module>
    from ..common.pkg_formats.python import get_site_packages_anchor_files
  File "C:\ProgramData\Anaconda3\Lib\site-packages\conda\common\pkg_formats\python.py", line 1169, in <module>
    DEFAULT_MARKER_CONTEXT = get_default_marker_context()
  File "C:\ProgramData\Anaconda3\Lib\site-packages\conda\common\pkg_formats\python.py", line 1151, in get_default_marker_context
    'platform_python_implementation': platform.python_implementation(),
  File "C:\Users\Gautam\AppData\Local\Programs\Python\Python37\Lib\platform.py", line 1264, in python_implementation
    return _sys_version()[0]
  File "C:\Users\Gautam\AppData\Local\Programs\Python\Python37\Lib\platform.py", line 1225, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 15:37:01) [MSC v.1916 64 bit (AMD64)]'
(base) PS C:\Users\xxx>

```

- Type:
    - [*] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [*] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by janlazo** [comment]
Nothing in the error message suggests that this is caused by vim-plug.
Send your issues with conda at https://github.com/conda/conda/issues.
